#define SERIAL_SPEED   115200

#define JOY_SLAVE_ADDRESS          0x0A
#define FLOW_SLAVE_ADDRESS         0x0B
#define LOADCELL_SLAVE_ADDRESS     0x0C
#define RELAYDRIVER_SLAVE_ADDRESS  0x0D

#define PACKET_LEN 20
uint8_t dataBuf[PACKET_LEN]; 
